import type { Metadata } from 'next';
import Link from 'next/link';
import { GateIllustration } from '@/components/GateIllustration';
import { FAQSchema } from '@/components/Schema';
import { site } from '@/data/site';
export const metadata: Metadata = { title: 'Gate & Access-Control Service for HOAs | Orlando & Tampa', description: 'Preventive maintenance, repairs, 24/7 emergency service and new installations for HOAs, property managers and CAMs. Request a free property assessment.', alternates: { canonical: '/' } };
const needs = [
  { number: '01', title: 'Preventive maintenance', text: 'Plan ongoing care for the gates and access equipment your community relies on.', href: '#maintenance' },
  { number: '02', title: 'Repairs & service', text: 'Get help with recurring faults, unreliable entry or equipment that has stopped working.', href: '/contact?service=repair' },
  { number: '03', title: 'Retrofits & upgrades', text: 'Review aging operators and entry systems, and explore what can work with your property.', href: '/contact?service=retrofit' },
  { number: '04', title: 'New installations', text: 'Plan a new gate or access-control system around your entry points and everyday use.', href: '/services/security-gate-systems' },
];
const faqs = [
  { q: 'Do you offer preventive-maintenance contracts?', a: 'Yes. We offer preventive maintenance for gates and access-control systems. The equipment, condition and use of your property help determine the scope. Start with a free property assessment request.' },
  { q: 'Can you work on an existing system?', a: 'We handle service, repairs, retrofits and upgrades as well as new installations. Tell us about your existing equipment and the issue so we can discuss the right next step. Compatibility is assessed for each property.' },
  { q: 'Where do you provide service?', a: 'Our focus is the Orlando market, and we also serve Tampa. Share your property’s city or area so we can confirm service for your location.' },
  { q: 'What should I do if a gate or access system is down?', a: 'Call Florida Security Concepts for 24/7 emergency service. A website request does not automatically dispatch a technician or confirm an arrival time.' },
];
export default function HomePage() {
  return <div className="fsc-home">
    <section className="fsc-home-hero"><div className="fsc-container fsc-home-hero-grid"><div>
      <p className="fsc-kicker">For HOAs, property managers & CAMs</p>
      <h1>Gate & access-control service.<br/><span>One less thing on your list.</span></h1>
      <p className="fsc-hero-intro">Preventive maintenance, repairs, 24/7 emergency service and new installations in Orlando and Tampa.</p>
      <Link href="/contact" className="fsc-btn-primary fsc-main-cta" data-fsc-event="assessment_cta" data-fsc-placement="hero">Request a Free Property Assessment <span aria-hidden="true">↗</span></Link>
      <p className="fsc-hero-note">Tell us what your community needs. We’ll discuss the next step.</p>
      <div className="fsc-hero-needs" aria-label="Service choices"><Link href="#maintenance" data-fsc-event="maintenance_interest" data-fsc-placement="hero">Maintenance</Link><Link href="/contact?service=repair">Repairs</Link><Link href="/contact?service=retrofit">Retrofits</Link><Link href="/services/security-gate-systems">New installations</Link></div>
    </div><GateIllustration /></div></section>
    <section className="fsc-light fsc-section-new" id="services"><div className="fsc-container"><div className="fsc-section-heading"><div><p className="fsc-kicker">Start with what you need</p><h2>From the recurring issue<br/>to the next major project.</h2></div><p>Practical help for the systems that keep residents, visitors and vendors moving through your property.</p></div><div className="fsc-service-list">{needs.map(n => <Link key={n.number} href={n.href} className="fsc-service-item" data-fsc-event={n.href === '#maintenance' ? 'maintenance_interest' : undefined} data-fsc-placement={n.href === '#maintenance' ? 'home_services' : undefined}><span className="fsc-service-number">{n.number}</span><h3>{n.title}</h3><p>{n.text}</p><span className="fsc-service-arrow" aria-hidden="true">↗</span></Link>)}</div></div></section>
    <section className="fsc-maintenance fsc-section-new" id="maintenance"><div className="fsc-container fsc-two-column"><div><p className="fsc-kicker">Preventive maintenance</p><h2>Give maintenance a place<br/>in your property’s plan.</h2><p>A gate that needs attention again. An entry system residents no longer trust. Equipment with an unclear service history.</p><p>Let’s look at what your community has and discuss a maintenance plan suited to its equipment and use.</p><Link href="/contact?service=preventive-maintenance" className="fsc-btn-primary" data-fsc-event="assessment_cta maintenance_interest" data-fsc-placement="home_maintenance">Discuss preventive maintenance <span aria-hidden="true">↗</span></Link></div><div className="fsc-maintenance-note"><span className="fsc-note-label">A useful starting point</span><h3>What is happening<br/>at your property?</h3><ul><li>Recurring gate or entry problems</li><li>Aging equipment and upgrade questions</li><li>A need for ongoing maintenance</li><li>A new community or property to manage</li></ul><p>Your equipment and site conditions guide the conversation.</p></div></div></section>
    <section className="fsc-light fsc-section-new"><div className="fsc-container"><div className="fsc-section-heading"><div><p className="fsc-kicker">Technical work. Clear conversation.</p><h2>Understand your options.<br/>Know the next step.</h2></div><p>Managing a community means keeping many people informed. Clear explanations make equipment decisions easier to discuss with your board and residents.</p></div><div className="fsc-communication"><div><span>01 / Your property</span><h3>Start with the issue.</h3><p>Tell us what is working, what is unreliable and what you are planning.</p></div><div><span>02 / Your equipment</span><h3>Consider the whole entry.</h3><p>Gates, operators, access devices and supporting systems all affect the scope.</p></div><div><span>03 / Your options</span><h3>Discuss the right work.</h3><p>Explore maintenance, repair, replacement or a new installation for your needs.</p></div></div><div className="fsc-secondary-services"><span>Beyond the gate</span><Link href="/services/access-control">Access control ↗</Link><Link href="/services/video-surveillance">Video surveillance ↗</Link><Link href="/services/security-system-integration">System integration ↗</Link></div></div></section>
    <section className="fsc-emergency-block"><div className="fsc-container"><div><p className="fsc-kicker">24/7 emergency service</p><h2>Gate down? Entry system offline?</h2><p>Call FSC to discuss the issue. A form request does not dispatch a technician.</p></div><a href={`tel:${site.emergencyPhone}`} className="fsc-emergency-call" data-fsc-event="emergency_call" data-fsc-placement="home_emergency">Call {site.emergencyPhoneDisplay} <span aria-hidden="true">↗</span></a></div></section>
    <section className="fsc-light fsc-section-new"><div className="fsc-container fsc-two-column"><div><p className="fsc-kicker">Orlando first. Tampa too.</p><h2>Local service for<br/>the communities you manage.</h2><p>From one property to a management portfolio, start with the city, the equipment and the work you need.</p><Link href="/service-areas" className="fsc-text-link">Explore our service areas →</Link><div className="fsc-area-links"><Link href="/industries/hoa-gated-communities">HOAs & gated communities</Link><Link href="/industries/property-managers">Property managers & CAMs</Link></div></div><div className="fsc-faq"><h3>A few things to know</h3>{faqs.map(f => <details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</div></div></section>
    <section className="fsc-final-cta"><div className="fsc-container"><p className="fsc-kicker">Let’s talk about your property</p><h2>A clear next step starts here.</h2><p>Request a free property assessment. We’ll contact you to discuss your needs and arrange the next step.</p><Link href="/contact" className="fsc-btn-primary" data-fsc-event="assessment_cta" data-fsc-placement="home_final">Request a Free Property Assessment <span aria-hidden="true">↗</span></Link></div></section>
    <FAQSchema items={faqs} />
  </div>;
}
