// lib/leads/crmIntake.ts unit tests (S-CRM-001, contract §14.2, invariants 5, 6, 8).
// Signer vectors were generated OUT OF BAND by running the CRM repo's own
// fsc-crm/supabase/functions/_shared/hmac.mjs `signRequest` (and checked with its
// `verifySignedRequest`); they are pinned here as literals. Nothing is imported
// from the CRM repo.
import { afterEach, describe, expect, it, vi } from 'vitest';
import { createHmac } from 'node:crypto';
import {
  buildCrmBody, classifyCrmResponse, crmDependencies, CRM_CUSTOMER_RESERVE_MS, CRM_INTAKE_HOST, CRM_MIN_REMAINING_MS, CRM_MIN_SECRET_LENGTH, CRM_RPC_CAP_MS, CRM_TIMEOUT_CAP_MS, signCrmRequest,
} from '../../lib/leads/crmIntake';

const URL_OK = 'https://izhandnebyywemsjisye.supabase.co/functions/v1/crm-intake';
const SECRET = 'synthetic-unit-crm-secret-0123456789abcdef';
const env = (values: Record<string, string | undefined>) => values as unknown as NodeJS.ProcessEnv;
const VALID = env({ FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: SECRET });
const nodeSign = (secret: string, timestamp: number | string, body: string) => `v1=${createHmac('sha256', secret).update(`${timestamp}.${body}`, 'utf8').digest('hex')}`;
const jsonResponse = (status: number, body: unknown) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });

afterEach(() => { vi.restoreAllMocks(); });

describe('constants (§14.2)', () => {
  it('pins the contract values (§14.2 + D-031)', () => {
    expect({ CRM_MIN_SECRET_LENGTH, CRM_TIMEOUT_CAP_MS, CRM_MIN_REMAINING_MS, CRM_RPC_CAP_MS, CRM_CUSTOMER_RESERVE_MS, CRM_INTAKE_HOST }).toEqual({
      CRM_MIN_SECRET_LENGTH: 32, CRM_TIMEOUT_CAP_MS: 4000, CRM_MIN_REMAINING_MS: 6000, CRM_RPC_CAP_MS: 1500, CRM_CUSTOMER_RESERVE_MS: 3000, CRM_INTAKE_HOST: 'izhandnebyywemsjisye.supabase.co',
    });
  });
});

describe('signCrmRequest (invariant 6)', () => {
  // Generated by fsc-crm hmac.mjs signRequest, verified OK by its verifySignedRequest.
  const VECTORS = [
    { secret: 'aaaabbbbccccddddeeeeffffgggghhhh', timestamp: 1000000000, body: '{"requestId":"test-id","lead":{}}', sig: 'v1=db8cdda36ab4c15584d39b5a0740d7b5becab5ad6e1afd3ed9ae1432ed2e0787' },
    { secret: 'synthetic-crm-vector-secret-0123456789', timestamp: 1789000000, body: '{"requestId":"9b2f1c3e-7a44-4d1b-8e2f-0c6d5a4b3e21","lead":{"fullName":"Zoë Synthetic","message":"Café ✓ — 日本"}}', sig: 'v1=f7a39ea51d11225dd74c44c3b700631f1cca956c3954a7fd1a10a9fb94af972d' },
    { secret: 'a'.repeat(32), timestamp: 1, body: '', sig: 'v1=d7e1e80175005e5a0612f667167dc14b8e89ad33f167077ff82b91874b5dea0f' },
  ];
  it.each(VECTORS)('matches the CRM signRequest vector and an independent node:crypto HMAC (%#)', async vector => {
    const sig = await signCrmRequest(vector.secret, vector.timestamp, vector.body);
    expect(sig).toBe(vector.sig);
    expect(sig).toBe(nodeSign(vector.secret, vector.timestamp, vector.body));
    expect(sig).toMatch(/^v1=[0-9a-f]{64}$/);
  });

  it('is sensitive to every input: one changed byte in body, timestamp or secret changes the signature', async () => {
    const base = await signCrmRequest(SECRET, 1789000000, '{"a":1}');
    expect(await signCrmRequest(SECRET, 1789000000, '{"a":2}')).not.toBe(base);
    expect(await signCrmRequest(SECRET, 1789000001, '{"a":1}')).not.toBe(base);
    expect(await signCrmRequest(`${SECRET.slice(0, -1)}X`, 1789000000, '{"a":1}')).not.toBe(base);
    // The body is signed exactly as given (no re-serialisation): semantically equal JSON with different bytes differs.
    expect(await signCrmRequest(SECRET, 1789000000, '{"a": 1}')).not.toBe(base);
  });

  it('accepts a secret of exactly 32 characters and rejects 31 (MISSING_SECRET)', async () => {
    await expect(signCrmRequest('s'.repeat(32), 1, 'x')).resolves.toMatch(/^v1=/);
    await expect(signCrmRequest('s'.repeat(31), 1, 'x')).rejects.toThrow(/^MISSING_SECRET$/);
  });

  it.each([
    ['empty secret', '', 1, 'x', 'MISSING_SECRET'],
    ['non-string secret', null, 1, 'x', 'MISSING_SECRET'],
    ['zero timestamp', SECRET, 0, 'x', 'BAD_TIMESTAMP'],
    ['negative timestamp', SECRET, -1, 'x', 'BAD_TIMESTAMP'],
    ['fractional timestamp', SECRET, 1.5, 'x', 'BAD_TIMESTAMP'],
    ['NaN timestamp', SECRET, Number.NaN, 'x', 'BAD_TIMESTAMP'],
    ['Infinity timestamp', SECRET, Number.POSITIVE_INFINITY, 'x', 'BAD_TIMESTAMP'],
    ['unsafe integer timestamp', SECRET, Number.MAX_SAFE_INTEGER + 1, 'x', 'BAD_TIMESTAMP'],
    ['string timestamp', SECRET, '1789000000', 'x', 'BAD_TIMESTAMP'],
    ['null body', SECRET, 1, null, 'BAD_BODY'],
    ['object body', SECRET, 1, { a: 1 }, 'BAD_BODY'],
  ])('rejects %s with %s (same codes and precedence as hmac.mjs)', async (_label, secret, timestamp, body, code) => {
    await expect(signCrmRequest(secret as string, timestamp as number, body as string)).rejects.toThrow(new RegExp(`^${code}$`));
  });

  it('checks the secret before the timestamp and the timestamp before the body', async () => {
    await expect(signCrmRequest('short', 0, null as unknown as string)).rejects.toThrow(/^MISSING_SECRET$/);
    await expect(signCrmRequest(SECRET, 0, null as unknown as string)).rejects.toThrow(/^BAD_TIMESTAMP$/);
  });
});

describe('buildCrmBody', () => {
  it('is exactly JSON.stringify({ requestId, lead: payload }) and preserves the payload key order it is given', () => {
    const payload = { email: 'x@example.invalid', city: 'Orlando', fullName: 'Synthetic Name' };
    expect(buildCrmBody('req-1', payload)).toBe('{"requestId":"req-1","lead":{"email":"x@example.invalid","city":"Orlando","fullName":"Synthetic Name"}}');
    const reordered = { fullName: 'Synthetic Name', city: 'Orlando', email: 'x@example.invalid' };
    expect(buildCrmBody('req-1', reordered)).not.toBe(buildCrmBody('req-1', payload));
  });

  it('escapes non-ASCII and quote characters exactly as JSON.stringify does', () => {
    const payload = { message: 'Café "quoted" ✓\n— 日本' };
    expect(buildCrmBody('r', payload)).toBe(`{"requestId":"r","lead":${JSON.stringify(payload)}}`);
    expect(JSON.parse(buildCrmBody('r', payload)).lead).toEqual(payload);
  });
});

describe('classifyCrmResponse (every branch of the §6 table)', () => {
  it.each([
    [200, { code: 'RECEIVED', receiptId: 'crm-1' }, { kind: 'succeeded', receiptId: 'crm-1' }],
    [200, { code: 'REPLAYED', receiptId: 'crm-1' }, { kind: 'succeeded', receiptId: 'crm-1' }],
    [200, { code: 'RECEIVED' }, { kind: 'succeeded', receiptId: null }],
    [200, { code: 'RECEIVED', receiptId: 42 }, { kind: 'succeeded', receiptId: null }],
    [200, { code: 'RECEIVED', receiptId: 'r'.repeat(200) }, { kind: 'succeeded', receiptId: 'r'.repeat(200) }],
    [200, { code: 'RECEIVED', receiptId: 'r'.repeat(201) }, { kind: 'succeeded', receiptId: null }],
    [200, { code: 'received' }, { kind: 'ambiguous' }],
    [200, { code: 'QUEUED' }, { kind: 'ambiguous' }],
    [200, { ok: true }, { kind: 'ambiguous' }],
    [200, null, { kind: 'ambiguous' }],
    [200, 'RECEIVED', { kind: 'ambiguous' }],
    [200, ['RECEIVED'], { kind: 'ambiguous' }],
    [201, { code: 'RECEIVED', receiptId: 'x' }, { kind: 'ambiguous' }],
    [202, { code: 'REPLAYED' }, { kind: 'ambiguous' }],
    [204, null, { kind: 'ambiguous' }],
    [299, { code: 'RECEIVED' }, { kind: 'ambiguous' }],
    [301, { code: 'RECEIVED' }, { kind: 'ambiguous' }],
    [400, { code: 'BAD' }, { kind: 'ambiguous' }],
    [401, { code: 'BAD_SIGNATURE' }, { kind: 'configuration' }],
    [401, null, { kind: 'configuration' }],
    [403, null, { kind: 'ambiguous' }],
    [404, null, { kind: 'ambiguous' }],
    [405, null, { kind: 'configuration' }],
    [409, { code: 'CONFLICT' }, { kind: 'conflict' }],
    [409, null, { kind: 'conflict' }],
    [413, null, { kind: 'configuration' }],
    [422, { code: 'INVALID' }, { kind: 'validation' }],
    [429, null, { kind: 'ambiguous' }],
    [500, { code: 'RECEIVED' }, { kind: 'ambiguous' }],
    [502, null, { kind: 'ambiguous' }],
    [503, null, { kind: 'ambiguous' }],
    [504, null, { kind: 'ambiguous' }],
    [0, null, { kind: 'ambiguous' }],
  ])('%i %j → %j', (status, body, expected) => {
    expect(classifyCrmResponse(status, body)).toEqual(expected);
  });
});

describe('crmDependencies configuration (kill switch)', () => {
  it.each([
    ['nothing set', {}],
    ['URL blank', { FSC_CRM_INTAKE_URL: '   ', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['secret missing', { FSC_CRM_INTAKE_URL: URL_OK }],
    ['secret blank', { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: '' }],
    ['secret 31 characters', { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: 's'.repeat(31) }],
    ['secret 31 characters plus whitespace', { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: ` ${'s'.repeat(31)}\t` }],
    ['valid secret with a leading space (never trimmed, D-031 m-3)', { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: ` ${SECRET}` }],
    ['valid secret with a trailing newline (never trimmed, D-031 m-3)', { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: `${SECRET}\n` }],
    ['valid secret with a trailing tab (never trimmed, D-031 m-3)', { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: `${SECRET}\t` }],
    ['another supabase project (host pinned, D-031 m-2)', { FSC_CRM_INTAKE_URL: 'https://abcdefghijklmnopqrst.supabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['subdomain of the pinned host', { FSC_CRM_INTAKE_URL: 'https://x.izhandnebyywemsjisye.supabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['trailing-dot host', { FSC_CRM_INTAKE_URL: 'https://izhandnebyywemsjisye.supabase.co./functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['empty-label supabase host', { FSC_CRM_INTAKE_URL: 'https://.supabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['explicit non-default port (D-031 m-2)', { FSC_CRM_INTAKE_URL: 'https://izhandnebyywemsjisye.supabase.co:8443/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['http scheme', { FSC_CRM_INTAKE_URL: URL_OK.replace('https:', 'http:'), FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['non-supabase host', { FSC_CRM_INTAKE_URL: 'https://crm.example.invalid/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['bare supabase.co host', { FSC_CRM_INTAKE_URL: 'https://supabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['host suffix trick', { FSC_CRM_INTAKE_URL: 'https://x.supabase.co.example.invalid/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['lookalike host', { FSC_CRM_INTAKE_URL: 'https://evilsupabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['host in path', { FSC_CRM_INTAKE_URL: 'https://example.invalid/.supabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['userinfo', { FSC_CRM_INTAKE_URL: 'https://user:pass@izhandnebyywemsjisye.supabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['username only', { FSC_CRM_INTAKE_URL: 'https://user@izhandnebyywemsjisye.supabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['query string', { FSC_CRM_INTAKE_URL: `${URL_OK}?apikey=x`, FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['fragment', { FSC_CRM_INTAKE_URL: `${URL_OK}#frag`, FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['trailing slash path', { FSC_CRM_INTAKE_URL: `${URL_OK}/`, FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['different function', { FSC_CRM_INTAKE_URL: URL_OK.replace('crm-intake', 'crm-export'), FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['v2 path', { FSC_CRM_INTAKE_URL: URL_OK.replace('/v1/', '/v2/'), FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['not a URL', { FSC_CRM_INTAKE_URL: 'izhandnebyywemsjisye.supabase.co/functions/v1/crm-intake', FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
  ])('%s → null, and never calls fetch', (_label, values) => {
    const fetchImpl = vi.fn();
    expect(crmDependencies(env(values), fetchImpl as unknown as typeof fetch)).toBeNull();
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  it.each([
    ['canonical', { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['secret exactly 32 characters', { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: 's'.repeat(32) }],
    ['URL with surrounding whitespace (the URL is trimmed, §14.2)', { FSC_CRM_INTAKE_URL: `  ${URL_OK}\n`, FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
    ['uppercase host (URL-normalised to the pinned host)', { FSC_CRM_INTAKE_URL: URL_OK.replace('izhandnebyywemsjisye.supabase.co', 'IZHANDNEBYYWEMSJISYE.SUPABASE.CO'), FSC_CRM_INTAKE_HMAC_SECRET: SECRET }],
  ])('%s → a client with post()', (_label, values) => {
    const deps = crmDependencies(env(values), vi.fn() as unknown as typeof fetch);
    expect(deps).not.toBeNull();
    expect(typeof deps!.post).toBe('function');
  });

  it('reads process.env by default (unset → null)', () => {
    vi.stubEnv('FSC_CRM_INTAKE_URL', '');
    vi.stubEnv('FSC_CRM_INTAKE_HMAC_SECRET', '');
    try { expect(crmDependencies()).toBeNull(); } finally { vi.unstubAllEnvs(); }
  });
});

describe('crmDependencies().post (wire contract)', () => {
  function client(fetchImpl: (url: string, init: RequestInit) => Promise<Response>, values: Record<string, string> = { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: SECRET }, now: () => number = () => 1789000000) {
    const mock = vi.fn(fetchImpl);
    const deps = crmDependencies(env(values), mock as unknown as typeof fetch, now);
    if (!deps) throw new Error('fixture configuration must be valid');
    return { deps, mock };
  }

  it('POSTs the raw body unchanged to the configured URL with exactly the three headers, redirect:error, cache:no-store and the caller\'s signal', async () => {
    const { deps, mock } = client(async () => jsonResponse(200, { code: 'RECEIVED', receiptId: 'crm-9' }));
    const raw = '{"requestId":"r","lead":{"message":"Café ✓"}}';
    const controller = new AbortController();
    expect(await deps.post(raw, controller.signal)).toEqual({ kind: 'succeeded', receiptId: 'crm-9' });
    expect(mock).toHaveBeenCalledTimes(1);
    const [url, init] = mock.mock.calls[0];
    expect(url).toBe(URL_OK);
    expect(init.method).toBe('POST');
    expect(init.body).toBe(raw);
    expect(init.redirect).toBe('error');
    expect(init.cache).toBe('no-store');
    expect(init.signal).toBe(controller.signal);
    expect(init.headers).toEqual({ 'Content-Type': 'application/json', 'X-FSC-CRM-Timestamp': '1789000000', 'X-FSC-CRM-Signature': nodeSign(SECRET, 1789000000, raw) });
  });

  it('signs with the secret exactly as configured (a secret with internal spaces is used byte-for-byte)', async () => {
    const spaced = 'synthetic secret with internal spaces 0123';
    const { deps, mock } = client(async () => jsonResponse(200, { code: 'RECEIVED' }), { FSC_CRM_INTAKE_URL: URL_OK, FSC_CRM_INTAKE_HMAC_SECRET: spaced });
    await deps.post('{}', new AbortController().signal);
    expect((mock.mock.calls[0][1].headers as Record<string, string>)['X-FSC-CRM-Signature']).toBe(nodeSign(spaced, 1789000000, '{}'));
  });

  it('posts to the normalised pinned URL even when the configured host was uppercase', async () => {
    const { deps, mock } = client(async () => jsonResponse(200, { code: 'RECEIVED' }), { FSC_CRM_INTAKE_URL: URL_OK.replace('izhandnebyywemsjisye.supabase.co', 'IZHANDNEBYYWEMSJISYE.SUPABASE.CO'), FSC_CRM_INTAKE_HMAC_SECRET: SECRET });
    await deps.post('{}', new AbortController().signal);
    expect(mock.mock.calls[0][0]).toBe(URL_OK);
  });

  it('takes a fresh timestamp per call and re-signs; the body bytes are untouched', async () => {
    let now = 1789000000;
    const { deps, mock } = client(async () => jsonResponse(200, { code: 'REPLAYED' }), undefined, () => now);
    await deps.post('{"x":1}', new AbortController().signal);
    now = 1789000007;
    await deps.post('{"x":1}', new AbortController().signal);
    const headers = mock.mock.calls.map(call => call[1].headers as Record<string, string>);
    expect(headers.map(h => h['X-FSC-CRM-Timestamp'])).toEqual(['1789000000', '1789000007']);
    expect(headers.map(h => h['X-FSC-CRM-Signature'])).toEqual([nodeSign(SECRET, 1789000000, '{"x":1}'), nodeSign(SECRET, 1789000007, '{"x":1}')]);
    expect(mock.mock.calls.map(call => call[1].body)).toEqual(['{"x":1}', '{"x":1}']);
  });

  it('the default clock is unix seconds', async () => {
    const mock = vi.fn(async () => jsonResponse(200, { code: 'RECEIVED' }));
    const deps = crmDependencies(VALID, mock as unknown as typeof fetch)!;
    const before = Math.floor(Date.now() / 1000);
    await deps.post('{}', new AbortController().signal);
    const ts = Number(((mock.mock.calls[0] as unknown[])[1] as RequestInit & { headers: Record<string, string> }).headers['X-FSC-CRM-Timestamp']);
    expect(ts).toBeGreaterThanOrEqual(before);
    expect(ts).toBeLessThanOrEqual(Math.floor(Date.now() / 1000));
  });

  it.each([
    ['network error', async () => { throw new TypeError('fetch failed'); }],
    ['abort', async (_url: string, init: RequestInit) => { throw init.signal?.reason ?? new DOMException('aborted', 'AbortError'); }],
    ['redirect refused', async () => { throw new TypeError('fetch failed: redirect mode is set to error'); }],
  ])('%s → ambiguous (never throws)', async (_label, impl) => {
    const { deps } = client(impl as (url: string, init: RequestInit) => Promise<Response>);
    const controller = new AbortController();
    controller.abort();
    await expect(deps.post('{}', controller.signal)).resolves.toEqual({ kind: 'ambiguous' });
  });

  it('unparseable 200 body → classified with a null body → ambiguous; unparseable 409 → conflict', async () => {
    const html = (status: number) => async () => new Response('<html>gateway</html>', { status, headers: { 'content-type': 'text/html' } });
    expect(await client(html(200)).deps.post('{}', new AbortController().signal)).toEqual({ kind: 'ambiguous' });
    expect(await client(html(409)).deps.post('{}', new AbortController().signal)).toEqual({ kind: 'conflict' });
  });

  it('a clock that yields an invalid timestamp is contained as ambiguous without any fetch', async () => {
    const { deps, mock } = client(async () => jsonResponse(200, { code: 'RECEIVED' }), undefined, () => 1.5);
    expect(await deps.post('{}', new AbortController().signal)).toEqual({ kind: 'ambiguous' });
    expect(mock).not.toHaveBeenCalled();
  });

  it('never logs: not the URL, secret, body, signature, timestamp or response', async () => {
    const spies = (['log', 'info', 'warn', 'error', 'debug'] as const).map(method => vi.spyOn(console, method).mockImplementation(() => undefined));
    const raw = '{"requestId":"r","lead":{"email":"log-probe@example.invalid"}}';
    for (const impl of [async () => jsonResponse(200, { code: 'RECEIVED', receiptId: 'crm-log-probe' }), async () => jsonResponse(503, { error: 'crm-body-probe' }), async () => { throw new TypeError('fetch failed'); }]) {
      await client(impl).deps.post(raw, new AbortController().signal);
    }
    expect(spies.reduce((total, spy) => total + spy.mock.calls.length, 0)).toBe(0);
  });
});
